Document: wily
Title: Debian wily Manual
Author: <insert document author here>
Abstract: This manual describes what wily is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wily/wily.sgml.gz

Format: postscript
Files: /usr/share/doc/wily/wily.ps.gz

Format: text
Files: /usr/share/doc/wily/wily.text.gz

Format: HTML
Index: /usr/share/doc/wily/html/index.html
Files: /usr/share/doc/wily/html/*.html
